baseurl = "https://terrancebrown.me"
DefaultContentLanguage = "en"
title = "A Life Abroad"
theme = "ananke"
enableRobotsTXT = true

[Params]
  description = "Meanderings on stationery, gaming, books, and the universe."
  author = "Terrance Brown"
  subtitle = "Meanderings and musings"


[params.ananke.social.follow]
  networks = ["mastodon", "bluesky", "github", "instagram", "linkedin", "goodreads", "letterboxd", "rss"]

[params.ananke.social.networks.goodreads]
  slug = "goodreads"
  label = "Goodreads"
  color = "#553b08"
  profile = "https://www.goodreads.com/%s"
  icon = "goodreads"

[params.ananke.social.networks.letterboxd]
  slug = "letterboxd"
  label = "Letterboxd"
  color = "#00c030"
  profile = "https://letterboxd.com/%s/"
  icon = "letterboxd"

[params.ananke.social.mastodon]
  profilelink = "https://social.lol/@terrance"
  rel = "me"

[params.ananke.social.bluesky]
  profilelink = "https://bsky.app/profile/merkaba.bsky.social"

[params.ananke.social.github]
  username = "terrancebrown"

[params.ananke.social.instagram]
  username = "merkabaza"

[params.ananke.social.linkedin]
  username = "terrancebrownza"

[params.ananke.social.goodreads]
  username = "merkaba"

[params.ananke.social.letterboxd]
  username = "merkabaza"

[params.ananke.social.rss]
  profilelink = "/index.xml"

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[[cascade]]
  [cascade._target]
    path = "/post/**"
  [cascade.params]
    toc = true

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 1

[[menu.main]]
    name = "Articles"
    url = "/post/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

