baseurl = "https://terrancebrown.me"
DefaultContentLanguage = "en"
title = "A Life Abroad"
theme = "ananke"

[Params]
  description = "Meanderings on stationery, gaming, books, and the universe."
  author = "Terrance Brown"
  subtitle = "Meanderings and musings"

[params.ananke.social]
  networks = ["mastodon", "bluesky", "github", "instagram", "linkedin"]

[params.ananke.social.mastodon]
  profilelink = "https://social.lol/@terrance"
  rel = "me"

[params.ananke.social.bluesky]
  profilelink = "https://bsky.app/profile/merkaba.bsky.social"

[params.ananke.social.github]
  username = "terrancebrown"

[params.ananke.social.instagram]
  username = "merkabaza"

[params.ananke.social.linkedin]
  username = "terrancebrownza"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
